FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# orderManagement

Polls is a simple API allowing consumers to view and create orders.

## Order Collection [/orderManagement]

### List All Orders [GET]

+ Response 200 (application/json)

        [
            {
                "orders": [
                    {
                        "id": 102030,
                        "address": "Av Vitacura 2939 piso 6",
                        "date": "01/01/2019",
                        "status": "en ruta"
                    }, {
                         "id": 102031,
                        "address": "Las condes 123",
                        "date": "02/01/2019",
                        "status": "en ruta"
                    }, {
                         "id": 102032,
                        "address": "Av Vitacura 2939 piso 6",
                        "date": "02/01/2019",
                        "status": "entregado"
                    }, {
                         "id": 102033,
                        "address": "Calle Isidora 2245",
                        "date": "01/01/2019",
                        "status": "en recepcion"
                    }
                ]
            }
        ]

### Create a New Order [POST]

You may create your own question using this action. It takes a JSON
object containing a order detail.

+ Request (application/json)

        {
            {
                        "address": "String",
                        "date": "01/01/2019",
                        "status": "status"
                    }
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 102036
            }